management:
  security:
     enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:18080/eureka/
asdf: dbc321
logging:
  config: http://localhost:18090/${spring.application.name}/development/master/log4j2.xml
spring:
  rabbitmq:
    addresses: localhost:5672
    username: dbc
    password: dbc
  cloud:
    bus:
      trace:
        enabled: true
